name: Reviewer

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions: write-all # Required for commenting on PRs
    steps:
      - uses: actions/checkout@v3

      - name : Set PR Title
        id: pr
        run: |
          echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Set Git Diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "::set-output name=diff::$(git diff origin/${{ github.base_ref }}..HEAD)"

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Reviewer
        id: review
        env:
          PR_TITLE: ${{ steps.pr.outputs.title }}
          GIT_DIFF: ${{ steps.diff.outputs.diff }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_SERVER: ${{ secrets.JIRA_SERVER }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: |
          REVIEW=$(python .github/scripts/run_reviewer.py)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "review<<$EOF" >> $GITHUB_OUTPUT
          echo "$REVIEW" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          script: |
            let review = `${{ steps.review.outputs.review }}`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            })
